### ISSUE TITLE
Confex in complex structures

### ISSUE THREAD

**Issue by arthur29** [Nebo15/confex#39]
Hello,

Today I needed to use confex to resolve some structures like tuples and lists with different forms. For example:
```
{{:system, :string, "SOME_VAR", "some_value"}, "some_value2", "some_value3"}
[{:system, :string, "SOME_VAR", "some_value"}, "some_value2", "some_value3"]
```

I was reading the tests and saw two of them were giving guarantees that confex doesn`t resolve this type of structures.
```
test "does not resolve in tuples" do
  assert Resolver.resolve({1, 2, 3, {:system, "KEEP_THIS"}}) == {:ok, {1, 2, 3, {:system, "KEEP_THIS"}}}
end
```
```
test "does not resolve in lists" do
  assert Resolver.resolve([1, 2, 3, {:system, "KEEP_THIS"}]) == {:ok, [1, 2, 3, {:system, "KEEP_THIS"}]}
end
```
Why confex does not resolve those kinds of structures?

Thanks,
Arthur

**Comment by AndrewDryga** [comment]
Hello @arthur29,

There are two reasons why lists are not resolved:

1. I tried to keep Confex as simple as possible;
2. "Better safe than sorry". We can not distinguish list from keyword and thus we may try to resolve configuration which should not be resolved (because of name conflicts), eg. when your configuration looks like:
```
config :my_app, :notifications,
  exchange: [system: :main],
  queue_name: {:sytem, "QUEUE_NAME"}
```

I don't think that we would ever replace tuples for similar reasons (but I believe mutating tuples would be even worse).

**Comment by arthur29** [comment]
OK,

Thanks!
