### ISSUE TITLE
Credo lint for compile time variables

### ISSUE THREAD

**Issue by mackeyja92** [Nebo15/confex#42]
My company is trying to blacklist compile time variables. To do so, I am creating a credo linter to fail our pipelines if any are found. Currently I am only linting for calls to `System.get_env`. Is there other calls I should be looking for?

In case anyone else is interested in the linter, here is [the source](https://github.com/mackeyja92/credo_runtime_only) and [the hex](https://hex.pm/packages/credo_runtime_only).

**Comment by AndrewDryga** [comment]
@mackeyja92 I think you should not rush writing a linter because there is an ongoing work in Elixir to have configuration providers and establish new best practices, so your work may be obsolete really soon.

`System.get_env` is not a bad thing if you use it not at compile time (module attributes or config.ex). I think this call is most commonly used one but depending on your application it can be pretty much anything, eg. you can read a file and use its value as a compile-time variable.
