### ISSUE TITLE
start confex (and my application) before logger ? 

### ISSUE THREAD

**Issue by bryanhuntesl** [Nebo15/confex#43]
Sorry it's a bit late in day - I'm trying to figure out how to start confex (and my application) before logger ( I want to selectively disable/enable sasl via an ENV var).

https://github.com/binarytemple/elixir_plug_poc/blob/04cefdec19030fcb212ce39237765b1baac204e6/lib/elixir_plug_poc.ex#L1-L5

Any pointers ?

**Comment by AndrewDryga** [comment]
Hello @bryanhuntesl. I think you can configure start sequence in `mix.exs` file by explicitly listing `applications` (instead of `extra_applications`). Confex does not start `:logger` app by itself.

But I'm not 100% sure that you can do it with Logger, because it starts two times: before any other application is started in case Elixir needs to log crash during boot (without any configuration) and then when it can be started with a configuration in place.

**Comment by bryanhuntesl** [comment]
> because it starts two times: before any other application is started in case Elixir needs to log crash during boot (without any configuration) and then when it can be started with a configuration in place.

That's not a problem - I'd just like to be selectively enable sasl when my application is running - perfect - thanks!

**Comment by AndrewDryga** [comment]
@bryanhuntesl You can also try using https://hexdocs.pm/logger/Logger.html#configure/1. You welcome.
